namespace FirebirdTraceAnalyzer.Models.Reports;

/// <summary>
/// Футер отчёта
/// </summary>
public sealed class ReportFooter
{
    /// <summary>Показывать футер?</summary>
    public bool Show { get; init; } = true;
    
    /// <summary>Текст футера</summary>
    public string Text { get; init; } = "Generated by Firebird Trace Analyzer";
    
    /// <summary>Показывать номера страниц?</summary>
    public bool ShowPageNumbers { get; init; } = true;
    
    /// <summary>Формат номера страницы</summary>
    public string PageNumberFormat { get; init; } = "Page {0} of {1}";
}